apiVersion: v1
kind: Service
metadata:
  name: datagerry-demo-02
  labels:
    app: datagerry-demo-02
spec:
  type: NodePort
  selector:
    app: datagerry-demo-02
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 31002
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datagerry-demo-02
spec:
  selector:
    matchLabels:
      app: datagerry-demo-02
  serviceName: "datagerry-demo-02"
  replicas: 1
  template:
    metadata:
      labels:
        app: datagerry-demo-02
    spec:
      containers:
      - name: datagerry
        image: nethinks/datagerry:latest
        env:
        - name: DATAGERRY_Database_host
          value: "127.0.0.1"
        - name: DATAGERRY_MessageQueueing_host
          value: "127.0.0.1"
      - name: db
        image: mongo:4.2-bionic
        volumeMounts:
        - name: dg-data-02
          mountPath: /data/db
        - name: dg-data-02
          mountPath: /data/configdb
      - name: broker
        image: rabbitmq:3.8
        volumeMounts:
        - name: dg-data-02
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: dg-data-02
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: do-block-storage
